apiVersion: v1
kind: Namespace
metadata:
  name: test-sre
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: memory-stresser
  namespace: test-sre
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stress-test
  template:
    metadata:
      labels:
        app: stress-test
    spec:
      containers:
      - name: stress
        image: polinux/stress-ng
        # Consumimos 150MB para forzar el OOM (LÃ­mite 110Mi)
        args: ["--vm", "1", "--vm-bytes", "150M", "--vm-hang", "1"]
        resources:
          limits:
            memory: "110Mi"
          requests:
            memory: "64Mi"